# .circleci/config.yml
version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.0.0"
    working_directory: Users⁩/⁨petrockz⁩/⁨Github⁩/⁨Daily⁩
    environment:
      FL_OUTPUT_DIR: output

    steps:
      - checkout
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: WebTests
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
